name: ExecutableEvents
version: ${project.version}
main: com.ssomar.executableevents.ExecutableEvents
api-version: 1.13
author: Ssomar
description: Customize all events that occurs on your server !
depend: [SCore]
softdepend: [SCore, PlayerPoints, Vault, WorldGuard, PlaceholderAPI, IridiumSkyblock, HeadDatabase, NBTAPI, ProtocolLib, HeadDB, CustomCrafting, PlotSquared]
commands:
  ee:
    description: ee command
    usage: /<command> [ reload | give | giveusage | givealluage | giveslot | giveall | show | editor | edit | actionbar | refresh | create | take | drop | clear | delete ]
folia-supported: true