# ----------------------------------
# -
#       ExecutableEvents
# -
#         By: Ssomar
# -
# ----------------------------------
# -
# WIKI HERE : https://docs.ssomar.com/executableevents/information-ee
# DISCORD HERE : https://discord.com/invite/TRmSwJaYNv
# -
disabledWorlds: []
premiumEnableCooldownForOp: true #Premium only
checkVersionMsg: true
disableBackup: false #<- Backup your items config at each start / reload of the server
deleteBackupsAfterDays: 7 #<- It will deletes backups older than this number of days